name: build kernel
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build kernel
        id: build
        env:
          KERNEL_BRANCH: "common-android12-5.10-lts"
          CONFIG_NAME: "main_config.cfg"
          KERNELSU: "https://github.com/ReSukiSU/ReSukiSU"
          KERNELSU_BRANCH: "main"
          SUSFS: "1"
          PATCH_FILE: "clean_uname.patch ondemand_tune.patch"
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          chmod +x build.sh
          ./build.sh
