name: build kernel
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build kernel
        id: build
        env:
          KERNEL_BRANCH: "common-android12-5.10-lts"
          CONFIG_NAME: "main_config.cfg"
          KERNELSU: "https://github.com/ReSukiSU/ReSukiSU"
          KERNELSU_BRANCH: "main"
          SUSFS: "1"
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          chmod +x build.sh
          ./build.sh

      - name: short sha
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: send
        uses: appleboy/telegram-action@master
        with:
          to: -100${{ secrets.CHAT_ID }}
          token: ${{ secrets.TOKEN }}
          document: ${{ steps.build.outputs.zip_file }}
          format: html
          message: |
            <b>Branch:</b> ${{ github.ref_name }}@${{ env.SHORT_SHA }}
            <b>#ci_${{ github.run_number }}</b>
            <pre>${{ github.event.head_commit.message }}</pre>
            <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Workflow</a>
            <a href="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}">Commit</a>